### PR TITLE
Fix #1980: Replay verification service implementation diverts from specification

### LINKED ISSUE #1980: Replay verification service implementation diverts from specification
### Affected product(s) and version(s)

1.10.0

### Environment

_No response_

### Steps to reproduce, current result, expected result

The replay verification service diverts from specification:
- `applicationKey` is not used in protocol versions `3.0`, `3.1`, and `3.2`
- `temporaryKeyId` is not used in protocol version `3.3`
- `requestTimestamp` filter has invalid boundary

### PR DESCRIPTION
**Pull request by romanstrobl**
Fixed according to the specification:

- `applicationKey` is used in protocol versions `3.0`, `3.1`, and `3.2`
- `temporaryKeyId` is used in protocol version `3.3`
- `requestTimestamp` filter boundary fixed

### CODE REVIEW

File: powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+import static org.junit.jupiter.api.Assertions.fail;
+import static org.mockito.Mockito.*;
+
+/**
+ * Test cases for replay protection for various protocol versions.
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+@TestInstance(TestInstance.Lifecycle.PER_CLASS)
+public class ReplayVerificationServiceTest {
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java]: nitpick: 
```suggestion
class ReplayVerificationServiceTest {
```

File: powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,177 @@
...
+
+    private DefaultReplayVerificationService verificationService;
+
+    @BeforeAll
+    public void setup() {
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java]:
```suggestion
   void setup() {
```

File: powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java [hunk 3]
```diff
@@ -0,0 +1,177 @@
...
+                return replayStore.add(uniqueValue);
+            }
+        };
+
+        verificationService = new DefaultReplayVerificationService(inMemoryPersistence, localizationProvider, configuration);
+    }
+
+    @ParameterizedTest
+    @MethodSource("provideTestCases")
+    public void testReplayValidation(TestCase tc) {
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java]:
```suggestion
   void testReplayValidation(TestCase tc) {
```

File: powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java [hunk 4]
```diff
@@ -0,0 +1,177 @@
...
+        } catch (RuntimeException | GenericServiceException e) {
+            if (tc.shouldPass) {
+                fail("Unexpected failure for: " + tc + " - " + e.getMessage());
+            }
+        }
+    }
+
+    static Stream<TestCase> provideTestCases() {
+        Instant now = Instant.now();
+        return Stream.of(
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/com/wultra/security/powerauth/app/server/service/replay/ReplayVerificationServiceTest.java:111]: It could be a CSV if you want to fine-tune it.

**Review by banterCZ — DISMISSED** [review]
Looks good.

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/model/UniqueValueParam.java [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * @author Roman Strobl, roman.strobl@wultra.com
+ */
+@Data
+public class UniqueValueParam {
+
+    private String ephemeralPublicKey;
+    private String nonce;
+    private String identifier;
+    private UniqueValueType uniqueValueType;
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/model/UniqueValueParam.java]: `@Data` also generates `toString`. Do we want to include `nonce`?

Comment (romanstrobl) [reply powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/model/UniqueValueParam.java]: Ok, I can exclude it.

However, I added logging for unique values in case of caught replay attacks, otherwise it is quite hard to debug production issues.

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java [hunk 6]
```diff
@@ -238,6 +238,13 @@ public class PowerAuthServiceConfiguration {
     @DurationMin(millis = 0)
     private Duration tokenTimestampForwardValidity;
 
+    /**
+     * Token timestamp validity to future, checked before validating the token.
+     */
+    @Value("${powerauth.service.replay.timestamp.threshold}")
```
Comment (jnpsk) [inline powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java:244]: Shouldn't this be also mentioned in docs and migration guide?

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/replay/DefaultReplayVerificationService.java [hunk 7]
```diff
@@ -52,40 +51,71 @@ class DefaultReplayVerificationService implements ReplayVerificationService {
...
+     *
+     * <p>Version 3.2+:
+     * <ul>
+     * <li>If TIMESTAMP < CURRENT_TIMESTAMP - TIMESTAMP_THRESHOLD, then reject request</li>
+     * <li>If TIMESTAMP > CURRENT_TIMESTAMP + TIMESTAMP_THRESHOLD, then reject request</li>
+     * </ul>
+     *
+     * @param protocolVersion Protocol version.
+     * @param requestTimestamp Request timestamp.
+     * @throws GenericServiceException Thrown incase request is rejected due to its timestamp.
```
Comment (jnpsk) [inline powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/replay/DefaultReplayVerificationService.java]: typo
```suggestion
     * @throws GenericServiceException Thrown in case request is rejected due to its timestamp.
```

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/util/ReplayAttackUtils.java [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+        }
+        return param;
+    }
+
+    /**
+     * Derive unique value parameters based on protocol version for activation scope.
+     *
+     * @param protocolVersion Protocol version.
+     * @param temporaryKeyId Temporary key ID.
+     *
```
Comment (jnpsk) [inline powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/util/ReplayAttackUtils.java]: Missing params in javadoc

**Review by jnpsk — DISMISSED** [review]
Looks good!
The `Configuration-Properties.md` should be updated together with migration guide.

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java (hunk 6 above)
Comment (romanstrobl) [reply powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java:244]: Yes, we can add this, although normally it should not be necessary to change this parameter.

**Review by jnpsk — APPROVED** [review]
