### PR TITLE
Fix #2296: Convert credential ID to Base64 standard if received in Base64 URL by API

### LINKED ISSUE #2296: Count with Base64 URL encoded credential ID in FIDO2 APIs
### Task specification

As of now, we are relying on the external party's normalization of the registration and assertion flows.
If the normalization is not performed, the system fails to create an assertion challenge. 
Internal format is Base64 and this is risky to change due to compatibility constraints.
To avoid issues in the integration of the product we will compensate on API level.
Both registration and assertion flows has to be addressed.

### PR DESCRIPTION
**Pull request by pavsindelar**
The ultimate solution is to normalize the Base64 encoding on input (discussed with @zcgandcomp).

### CODE REVIEW

File: powerauth-fido2-model/src/main/java/com/wultra/security/powerauth/fido2/model/converter/serialization/Base64UrlToBase64Deserializer.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+        final int remainder = normalized.length() % 4;
+        if (remainder == 0) {
+            // no padding needed
+            return normalized;
+        }
+
+        // add padding
+        return normalized + "=".repeat(4 - remainder);
+    }
```
[the remark this answers is not in the document]
Comment (pavsindelar) [reply powerauth-fido2-model/src/main/java/com/wultra/security/powerauth/fido2/model/converter/serialization/Base64UrlToBase64Deserializer.java:98]: Fixed.

**Review by zcgandcomp — DISMISSED** [review]
The logic of the mechanism looks good to to.

**Review by romanstrobl — CHANGES_REQUESTED** [review]
The deserializer will likely accept malformed base64 strings, such as `abcd$%` or with malformed padding. Perhaps we should validate the Base64 by trying to decode it?

We may also want to trim the whitespaces?

**Comment by pavsindelar** [comment]
> The deserializer will likely accept malformed base64 strings, such as `abcd$%` or with malformed padding. Perhaps we should validate the Base64 by trying to decode it?
> 
> We may also want to trim the whitespaces?

@romanstrobl, good point, we shall validate that 👍

File: powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToBase64DeserializerTest.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+    }
+
+    @Test
+    void testDeserialize_dashOnly_convertedToPlus() throws Exception {
+        final String result = objectMapper.readValue("\"AA-A\"", String.class);
+        assertEquals("AA+A", result);
+    }
+
+    @Test
+    void testDeserialize_underscoreOnly_convertedToSlash() throws Exception {
```
Comment (banterCZ) [inline powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToBase64DeserializerTest.java]: Nitpick, you may use `@ParameterizedTest`

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/controller/RESTControllerAdvice.java [hunk 3]
```diff
@@ -140,4 +140,14 @@ public class RESTControllerAdvice {
         return new ObjectResponse<>("ERROR", error);
     }
 
+    @ExceptionHandler(HttpMessageNotReadableException.class)
+    @ResponseStatus(HttpStatus.BAD_REQUEST)
+    public @ResponseBody ObjectResponse<PowerAuthError> handleHttpMessageNotReadableException(final HttpMessageNotReadableException e) {
+        logger.error("Error occurred while processing the request: {}", e.getMessage());
+        logger.debug("Exception details:", e);
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/controller/RESTControllerAdvice.java:147]: 🤔 I am thinking whether we shouldn't always log the stacktrace.

File: powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToBase64DeserializerTest.java (hunk 2 above)
Comment (pavsindelar) [reply powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToBase64DeserializerTest.java]: Good point, changed to parameterized tests.

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/controller/RESTControllerAdvice.java (hunk 3 above)
Comment (pavsindelar) [reply powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/controller/RESTControllerAdvice.java:147]: The pattern in this exception handler is consistently to log the stack trace on a debug level. Also, in case of this exception, the message is very descriptive so I don't think it is necessary really.

**Comment by pavsindelar** [comment]
> > The deserializer will likely accept malformed base64 strings, such as `abcd$%` or with malformed padding. Perhaps we should validate the Base64 by trying to decode it?
> > We may also want to trim the whitespaces?
> 
> @romanstrobl, good point, we shall validate that 👍

@romanstrobl, I have added a validation by decoding before returning the normalized string. As for stripping the whitespaces, I wouldn't do that for a JSON field. If the client calls the endpoint with extra whitespaces, he gets 400 with descriptive error message, allowing him to fix the issue. We validate just for a valid Base64 string.

**Review by romanstrobl — APPROVED** [review]
Looks good now.
