### PR TITLE
Fix #1840: Missing validation when updating callback configuration

### LINKED ISSUE #1840: Missing validation when updating callback configuration
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

When editing an existing callback, the there is no validation that requests do not include both content and location parameters. For new callbacks such validation is performed.

### Log output

_No response_

### PR DESCRIPTION
**Pull request by romanstrobl**

### CODE REVIEW

File: powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java [hunk 1]
```diff
@@ -525,4 +511,30 @@ private boolean isMaxAttemptsPositive(final CallbackUrlEntity callbackUrlEntity)
...
 
+    /**
+     * Validate request so that the authentication configuration is valid.
+     * @param authentication Authentication.
+     * @param callbackUrl Callback URL.
+     * @throws GenericServiceException Thrown when request validation fails.
+     */
+    private void validateAuthenticationConfigRequest(HttpAuthenticationPrivate authentication, String callbackUrl) throws GenericServiceException {
+        if (authentication != null && authentication.getCertificate() != null) {
+            HttpAuthenticationPrivate.Certificate certificate = authentication.getCertificate();
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/com/wultra/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java]: Could be _final_?

**Review by banterCZ — DISMISSED** [review]
Looks good.

**Review by banterCZ — APPROVED** [review]
